export const articles: { title: string; markdown: string }[] = [
  {
    title: "Anxiety Disorders",
    markdown: `### What Are Anxiety Disorders?\n\nAnxiety is a normal emotion. It’s your brain’s way of reacting to stress and alerting you of potential danger ahead.\n\nEveryone feels anxious now and then. For example, you may worry when faced with a problem at work, before taking a test, or before making an important decision.\n\nOccasional anxiety is OK. But anxiety disorders are different. They’re a group of mental illnesses that cause constant and overwhelming anxiety and fear.  The excessive anxiety can make you avoid work, school, family get-togethers, and other social situations that might trigger or worsen your symptoms.\n\nFor a markdown cheatsheet and tutorial [see here](https://commonmark.org/help/).`,
  },
  {
    title: "Everything You Need To Know About Addiction",
    markdown: `Addiction is not a sign of weakness, a character flaw, or a moral failure. It is a common condition that affects millions of people of all ages, backgrounds, and socioeconomic groups. And while there is no one cause of addiction, there is hope—it can be treated effectively.\n\n### Keep Reading To Learn\n- The truth about drug and alcohol addiction\n- How to recognize if you or a loved one may be struggling with addiction\n- How to successfully treat and manage substance misuse\n\n### Yes, Addiction Is A Mental Illness\nAddiction is a chronic disease that changes both brain structure and function, currently affecting the lives of nearly 10% of adults in the United States.\n\nAddiction swaps the everyday desires of the brain with those of the drug you are addicted to. You no longer enjoy what other people do as the brain changes. The changes start with recognition of pleasure and end with a drive toward compulsive behavior to fulfill that desire. Sometimes, when you try quitting, the addiction weakens your ability to manage impulses.\n\nAddiction exerts a long and powerful influence on the brain. This influence manifests in three ways:\n\n- Craving for the object of addiction\n- Loss of control over its use\n- Continuing involvement with it despite problems it causes\n\nWith drug and alcohol addiction, substances hijack the brain’s reward system. This could lead to developing a physical dependence on substances.\n\nSome people develop unpleasant and sometimes dangerous physical symptoms when they stop or decrease substance use. These changes result in a weakened ability to control impulses despite the negative consequences.\n\nSubstance misuse can lead to serious physical, emotional, and social problems. For example, continued use of drugs or alcohol can lead to job loss, broken relationships, and other failures. These problems often increase stress and anxiety.`,
  },
  {
    title: "Causes and Risk Factors of Depression",
    markdown: `Depression is one of the most common mental disorders in the United States. It can affect anyone at almost any age, but what causes depression in some people is [not always known](https://www.verywellmind.com/how-can-a-person-be-depressed-for-no-reason-1066765). Potential depression causes can include genetics, brain chemistry, life events, medical conditions, and lifestyle factors.\n\nThe Centers for Disease Control and Prevention reported that approximately 1 in 5 U.S. adults have received a depression diagnosis in their lifetime.1\nCenters for Disease Control and Prevention. National, State-Level, and County-Level Prevalence Estimates of Adults Aged ≥18 Years Self-Reporting a Lifetime Diagnosis of Depression — United States, 2020.\n\nThe World Health Organization estimates that 5% of men and 9% of women experience depressive disorders in any given year.`,
  },
  {
    title: "What You Should Know About Bipolar Disorder",
    markdown: `Are you wondering if you or someone you know has bipolar disorder? Since this mental health condition causes people to go from one extreme to another, it can prevent them from being able to fully enjoy their life.\n\nLiving with **bipolar disorder** makes one feel extremely happy and full of energy at one moment and then sad and depressed the next. These extreme mood swings can happen daily, weekly, or monthly and tend to get in the way of one’s ability to think clearly due to the constant back-and-forth feelings. Treatment for those living with this lifelong mental health condition often includes taking medications and going to counseling.\n\n## How is bipolar disorder diagnosed?\nAn experienced counselor knows how to perform an assessment that can let a person know whether they have this condition. The assessment requires the patient to fill out a questionnaire and then answer specific questions related to their thoughts and feelings and overall behavior. A counselor may request additional information from friends and family in order to acquire more information that can help them develop a proper diagnosis.\n\n### What causes bipolar disorder?\nEven though the exact cause of bipolar disorder is not yet known, it is believed to be directly related to biology and genetics. Research as reported by Biological Psychiatry shows that people living with bipolar disorder have biological differences in their brains, a theory still being explored today. Genetics seem to play a role, as studies have also determined that when someone has a close relative who has been diagnosed with this mental health condition, their chances of being diagnosed are higher.\n\n### How bipolar disorder can affect those diagnosed\nWhen left untreated, bipolar disorder can lessen one’s overall quality of life. Those diagnosed often live with other mental and/or physical health conditions that also need treatment. These include but are not limited to anxiety disorders, eating disorders, ADHD, heart disease, headaches, thyroid problems, and alcohol or drug problems.\n\nThe reason treatment is so essential is that those affected often feel helpless. This helplessness can lead to job problems, financial problems, legal problems, bad relationships, drug and alcohol abuse, and even suicide attempts.\n`,
  },
  {
    title: "Can TMS Treat Depression Completely?",
    markdown: `[TMS](https://www.evolvepsychiatry.com/massapequa-ny/tms-treatment-process-massapequa-ny/) is a non-invasive treatment for severe depression. It is a versatile treatment. A psychiatrist can also use it for other issues. Many patients feel the positive effects of this treatment. If you want to know if **TMS** can result in a full recovery from depression, here are the details.\n\n## The induction process\nThe patient’s first appointment is referred to as the TMS induction. This involves determining motor threshold, primary treatment, and brain mapping. The doctor will mark the region on the scalp, which is the DLPFC (dorsolateral prefrontal cortex). Testing the lowest amount of energy to excite the brain is the patient’s resting motor threshold. This will determine the patient’s dose of magnetic stimulation during the treatment series.\n\n### What happens during the treatment\nThis therapy is intensive. It involves attending five weekly sessions for many weeks. Every session can last for 20-50 minutes. The length of time depends on the clinical protocol and the device. The psychiatrist will set the machine’s intensity. The motor cortex of the patient’s brain will help pinpoint the location for attaching the stimulation coil.\n\nThe doctor will also perform calculations to translate the data for finding the dorsolateral prefrontal cortex. This is the area of the brain responsible for depression. One session is enough to change the excitability of the brain. The patient will only experience noticeable relief starting the third session.`,
  },
  {
    title: "What to Expect With Depression Therapy",
    markdown: `One of the most effective treatments for depression is talk therapy. Talk therapy, often known as psychotherapy, has the potential to be both the spark for positive change and the balm that helps calm the mind and soul. In addition, psychiatrists provide invaluable assistance to their clients by arming them with strategies that help them thrive and, in many cases, pave the way to future success.`,
  },
  {
    title: "Anxiety Disorder 101: Types, Symptoms, Causes & Treatment",
    markdown: `Learn about anxiety disorders, their different types, signs, causes and treatments available.\n\n### What are Anxiety Disorders?\nHave you had times when you feel worried about something, whether it’s about work or something else that stresses you out? That is anxiety, a perfectly normal emotional response to stressful situations that keep you alert and focused on the task at hand. Anxiety crops up from time to time and can be beneficial to us.\n\nHowever, if you find your anxiety to be continuous or overwhelming, and you always feel fearful or panicky, there may be a chance you are dealing with an [anxiety disorder](https://www.webmd.com/anxiety-panic/anxiety-disorders). Having an anxiety disorder can be detrimental to your wellbeing; you may find it hard to do things you enjoy and more so for tasks that stress you out. You may even avoid social interaction out of fear of worsening your condition.\n\nAccording to the Fourth National Health Morbidity Survey (NHMS-IV) conducted in 2011, the [prevalence rate](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6613468/) of generalised anxiety disorder (GAD) among Malaysians was recorded as 1.7 per cent.\n\nAn anxiety disorder can interfere with your daily routine, causing an overreaction to external stimuli that triggers your physical, emotional and/or psychological state. This can be a draining affair for you or your loved one.`,
  },
];
